version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  pgdata:
